server:
  port: 8888
  servlet:
    context-path: /${spring.application.name}
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/development/Dev/Configuration
      profile: dev