spring:
  data:
    mongodb:
      url: mongodb://localhost/carRentalApp
server:
  #servlet:
    #context-path: /${spring.application.name}
  port: 8080
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
security:
 oauth2:
  resource:
   userInfoUri: http://localhost:8084/user