server:
 port: 8083
zuul:
 prefix: /api
ribbon:
 eureka:
  enabled: true
spring:
  application:
    name: zuulProxy
eureka:
 instance:
    prefer-ip-address: true
 client:
  enabled: true
  register-with-eureka: true
  fetch-registry: true
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 60000

