server:
 port: 8083
zuul:
 routes:
  car-microservice:
   url: http://localhost:8080/car-microservice
  user-microservice:
   url: http://localhost:8082/user-microservice
ribbon:
 eureka:
  enabled: false
spring:
  application:
    name: zuulProxy
eureka:
 instance:
    prefer-ip-address: true
 client:
  enabled: true
  register-with-eureka: true
  fetch-registry: true

