server:
 port: 8083
zuul:
 prefix: /api
 #routes:
 # car-microservice:
 #  url: http://localhost:8080/car-microservice
 #  serviceId: car-microservice
 # user-microservice:
 #  url: http://localhost:8082/user-microservice
ribbon:
 eureka:
  enabled: false
spring:
  application:
    name: zuulProxy
eureka:
 instance:
    prefer-ip-address: true
 client:
  enabled: true
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'

