spring:
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.PostgreSQL94Dialect
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.lob.non_contextual_creation: false
      hibernate.id.new_generator_mappings: true
      hibernate.generate_statistics: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/reservations
    username: harris
    password: 12345
    platform: POSTGRESQL
    driverClassName: org.postgresql.Driver
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000
  liquibase:
    change-log: classpath:liquibase/master.xml
server:
  port: 8081
  #servlet:
    #context-path: /${spring.application.name}
management:
 endpoints:
  web:
   base-path: /management
   exposure:
    include: '*'
